on:
  push:
    brunch:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "printing name "
        run: echo Ahmed

      - name: "all contents"
        run: ls  
